### ISSUE TITLE
BadGateway: 502 <!DOCTYPE html> <html lang=en> <meta charset=utf-8> <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width"> <title>Error 502 (Server Error)!!1</title> <style> *{margin:0;padding:0}html,code{font:15px/22px arial,…

### ISSUE THREAD

**Issue by maxbbraun** [maxbbraun/trump2cash#13]
Happening occasionally.

```
Traceback (most recent call last):
  File "/home/max_braun/trump2cash/twitter.py", line 172, in process_queue
    logs.debug("Processing queue of size: %s" % size)
  File "/home/max_braun/trump2cash/logs.py", line 38, in debug
    self.logger.log_text(text, severity="DEBUG")
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/logging/logger.py", line 192, in log_text
    client.logging_api.write_entries([entry_resource])
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/logging/_http.py", line 165, in write_entries
    data=data)
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/_http.py", line 335, in api_request
    error_info=method + ' ' + url)
BadGateway: 502 <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 502 (Server Error)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>502.</b> <ins>That’s an error.</ins>
  <p>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.  <ins>That’s all we know.</ins>
 (POST https://logging.googleapis.com/v2/entries:write)
```

**Comment by maxbbraun** [comment]
Happens about once a week and is caught by the main restart loop.

**Comment by maxbbraun** [comment]
Let's see how well https://github.com/maxbbraun/trump2cash/commit/1719b0fb5ccccfac3cb3195308039c53efa571d3 handles this.

**Comment by Jibosoft** [comment]
please check this code for me 


1

<!DOCTYPE html>

2

<html lang="en">

3

  <head>

4

    <meta charset="UTF-8" />

5

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

6

    <meta http-equiv="X-UA-Compatible" content="ie=edge" />

7

​

8

    <title>Mini App</title>

9

​

10

    <style>

11

      body {

12

  background-color: #ffffff;

13

}

14

      h2   {

15

      font-family: verdana;

16

        }

17

    </style> 

18

 <div class="Select-Currency">

19

   

20

</div>

21

    

22

    <div class="conversion mdc-elevation--z3"></div>

23

    <div class ="massages"></div>

24

  </head>

25

    </style>

26

  </head>

27

  <body>

28

    <h2>Currency Converter</h2>

29

    <select>

30

  <option value="0">Select Currency</option>

31

  <option value="USD">US Dollars</option>

32

  <option value="UGX">Ugandan Shillings</option>

33

  <option value="KES">Kenyan Shillings</option>

34

  <option value="GHS">Ghanian Cedi</option>

35

  <option value="ZAR">South African Rand</option>

36

</select>

37

    <button>Convert</button>

38

    <script>

39

      

40

      const currencies = [{

41

        id: 'USD', name: 'US Dollars'

42

      }, {

43

        id: 'UGX', name: 'Ugandan Shillings'

44

      }, {

45

        id: 'KES', name: 'Kenyan Shillings'

46

      }, {

47

        id: 'GHS', name: 'Ghanian Cedi'

48

      }, {

49

        id: 'ZAR', name: 'South African Rand'

50

      }];

51

      

Completion Deadline:

**Comment by Anbarrasso** [comment]
hhhihi

**Comment by ArnavGoelHitman** [comment]
good

**Comment by seanmaverick0520** [comment]
<!doctype html>
--
  | <html dir="ltr" lang="en">
  | <head>
  | <meta charset="utf-8">
  | <title>New Tab</title>
  | <style>
  | body {
  | background: #FFFFFF;
  | margin: 0;
  | }
  |  
  | #oneGoogleBar {
  | height: 56px;
  | }
  |  
  | #backgroundImage {
  | border: none;
  | height: 100%;
  | pointer-events: none;
  | position: fixed;
  | top: 0;
  | visibility: hidden;
  | width: 100%;
  | }
  |  
  | [show-background-image] #backgroundImage {
  | visibility: visible;
  | }
  | </style>
  | </head>
  | <body>
  | <div id="oneGoogleBar"></div>
  | <iframe id="backgroundImage"
  | src="chrome-untrusted://new-tab-page/custom_background_image?url=https%3A%2F%2Flh4.googleusercontent.com%2Fproxy%2Fhl6qyPDq9FBOuU8G1A3X2khJJdAzfccHtIoX7hHtlkR4tgj_WJvpj4s8FX8cb8u9R6xhrp96xXJIIFrTK8Rdpqh0tTiSfL5k_OXcWw%3Dw3840-h2160-p-k-no-nd-mv">
  | </iframe>
  | <ntp-app></ntp-app>
  | <script type="module" src="new_tab_page.js"></script>
  | <link rel="stylesheet" href="chrome://resources/css/text_defaults_md.css">
  | <link rel="stylesheet" href="shared_vars.css">
  | <div id="oneGoogleBarEndOfBody"></div>
  | </body>
  | </html>

**Comment by mylesthegod** [comment]
nigga
