### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by Dotnaught** [maxbbraun/trump2cash#34]
Entering
`./benchmark.py > benchmark.md`
in a new install returns a Unicode error, apparently due to concatenating unexpected types.
`Traceback (most recent call last):
  File "./benchmark.py", line 191, in <module>
    print "\n\n".join(lines)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 144: ordinal not in range(128)`

**Comment by maxbbraun** [comment]
Try this:

```
export PYTHONIOENCODING="UTF-8"
```

**Comment by Dotnaught** [comment]
That did it. Thanks.
