### ISSUE TITLE
Missed tweet from Trump

### ISSUE THREAD

**Issue by domingohui** [maxbbraun/trump2cash#36]
Looks like the bot wasn't able to recognize The NY times in [this tweet](https://twitter.com/realDonaldTrump/status/832197515248275456).
Unless the bot thought the tweet carried a neutral sentiment?

**Comment by maxbbraun** [comment]
News and TV companies are explicitly excluded since https://github.com/maxbbraun/trump2cash/commit/14d861fb3dc0e911afd60ae3f5cb48cfed4598f1.
