### ISSUE TITLE
Robinhood API Integration - $0 fees

### ISSUE THREAD

**Issue by dskvr** [maxbbraun/trump2cash#39]
The API has been reversed engineered (https://github.com/sanko/Robinhood) but it does appear that Robinhood has plans to release an API (https://support.robinhood.com/hc/en-us/articles/210216823-Robinhood-API-Integrations)

**Comment by maxbbraun** [comment]
Duplicate of #22.

**Comment by WilliamJamesDalrympleWest** [comment]
Is this intergrateable?
