### ISSUE TITLE
Trade test failing after recent change

### ISSUE THREAD

**Issue by Dotnaught** [maxbbraun/trump2cash#41]
(Assuming this test isn't failing because the market is closed...)

`_______________________ test_make_order_request_success ________________________

trading = <trading.Trading instance at 0x7f79f369a878>

    def test_make_order_request_success(trading):
        assert not USE_REAL_MONEY
>       assert trading.make_order_request((
            '<FIXML xmlns="http://www.fixprotocol.org/FIXML-5-0-SP2">'
            '<Order TmInForce="0" Typ="1" Side="1" Acct="%s">'
            '<Instrmt SecTyp="CS" Sym="GM"/>'
            '<OrdQty Qty="23"/>'
            '</Order>'
            '</FIXML>' % TRADEKING_ACCOUNT_NUMBER))
E       assert False
E        +  where False = <bound method Trading.make_order_request of <trading.Trading instance at 0x7f79f369a878>>(('<FIXML xmlns="http://www.fixprotocol.org/FIXML-5-0-SP2"><Order TmInForce="0" Typ="1" Side="1" Acct="%s"><Instrmt SecTyp="CS" Sym="GM"/><OrdQty Qty="23"/></Order></FIXML>' % '12345678'))
E        +    where <bound method Trading.make_order_request of <trading.Trading instance at 0x7f79f369a878>> = <trading.Trading instance at 0x7f79f369a878>.make_order_request

trading_tests.py:374: AssertionError`

**Comment by maxbbraun** [comment]
The tests seem to pass now. Maybe a transient error on the TradeKing side?
