### ISSUE TITLE
Benchmark update

### ISSUE THREAD

**Issue by tibbon** [maxbbraun/trump2cash#54]
How's this strategy going?

**Comment by tagomatech** [comment]
Same question here. Is there un update, please?

**Comment by forddasav** [comment]
Not going great. It's really not that profitable because when it doesn't get it right you loose quite a bit

**Comment by maxbbraun** [comment]
Commit 4dfd2546c9b5a239778268f448f2da89b73a796b updates the [benchmark](https://github.com/maxbbraun/trump2cash/blob/master/benchmark.md).
